"""SQLAlchemy async engine, session factory and declarative base."""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase

from src.config import get_settings

# Explicit naming convention keeps Alembic autogenerated migrations stable and
# gives every constraint a deterministic name.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Database:
    """Owns the async engine and session factory.

    The bot creates one instance in `setup_hook` and disposes it on shutdown.
    """

    def __init__(self, url: str) -> None:
        self.engine: AsyncEngine = create_async_engine(url, pool_pre_ping=True)
        self.session_factory: async_sessionmaker[AsyncSession] = async_sessionmaker(
            self.engine,
            expire_on_commit=False,
        )

    def session(self) -> AsyncSession:
        """Return a new session. Use as `async with db.session() as s:`."""
        return self.session_factory()

    async def dispose(self) -> None:
        await self.engine.dispose()


def get_database() -> Database:
    """Build a `Database` from application settings."""
    return Database(get_settings().database_url)
