"""course thumbnail + image channel

Revision ID: 212c1335a5e3
Revises: a1b2c3d4e5f6
Create Date: 2026-07-15 12:26:05.337477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212c1335a5e3'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('thumbnail_url', sa.String(length=1024), nullable=True))
    op.add_column('guild_config', sa.Column('image_channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_config', 'image_channel_id')
    op.drop_column('course', 'thumbnail_url')
    # ### end Alembic commands ###
