"""emoji vote

Revision ID: cd1a55624f34
Revises: f492cdf201c6
Create Date: 2026-07-15 15:52:24.943783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1a55624f34'
down_revision: Union[str, None] = 'f492cdf201c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emoji_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('added', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emoji_suggestion')),
    sa.UniqueConstraint('message_id', name=op.f('uq_emoji_suggestion_message_id'))
    )
    op.add_column('guild_config', sa.Column('emoji_vote_channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_config', 'emoji_vote_channel_id')
    op.drop_table('emoji_suggestion')
    # ### end Alembic commands ###
