"""course thumbnail + image channel

Revision ID: d614ffa7520e
Revises: 212c1335a5e3
Create Date: 2026-07-15 13:55:56.812009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd614ffa7520e'
down_revision: Union[str, None] = '212c1335a5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('thread_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'thread_id')
    # ### end Alembic commands ###
