"""drop image_channel_id

Revision ID: f492cdf201c6
Revises: d614ffa7520e
Create Date: 2026-07-15 14:07:18.328723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f492cdf201c6'
down_revision: Union[str, None] = 'd614ffa7520e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_config', 'image_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_config', sa.Column('image_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
